language: java
jdk:
- oraclejdk8
before_install:
  - openssl aes-256-cbc -K $encrypted_4f9d2cbd4361_key -iv $encrypted_4f9d2cbd4361_iv
    -in travis_rsa.enc -out travis_rsa -d
  - chmod 600 travis_rsa
  - mv travis_rsa ~/.ssh/id_rsa
jobs:
  include:
  - stage: build
    script:
    - "./gradlew build --stacktrace --scan -s"
  - stage: docker
    script:
    - docker build --tag lucidworkslab/mybooks .
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker push lucidworkslab/mybooks
  - stage: deploy
    script:
      - ssh root@$DROPLET_IP 'docker run --rm -p 8080:8080 lucidworkslab/mybooks'
  - stage: regression
    script:
      - ls
