language: java

jdk:
  - oraclejdk8

jobs:
  include:
    - stage: build
      script:
        - ./gradlew build --stacktrace --scan -s
    - stage: deploy
      script: ./deploy
    - stage: regression
      script: ./test 1