version: '3'
services:
  mybooks-server:
    build:
      context: .
      dockerfile: mybooks-microservice-service/Dockerfile
      args:
        JAR_FILE: mybooks-microservice-service/build/libs/mybooks-microservice-service-0.0.1-SNAPSHOT.jar
    hostname: mybooks-server
    ports:
      - "8080:8080"
    environment:
      OPEN_LIBRARY_URL: http://wiremock-server:8080/
    restart: always
  wiremock-server:
    build:
      context: .
      dockerfile: mybooks-microservice-test-utils/Dockerfile
    hostname: wiremock-server
    ports:
      - "9090:8080"
    restart: always