AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: MyBook API

Resources:
  GetAllBooks:
    Type: AWS::Serverless::Function
    Properties:
      Handler: mybooks.Handler
      FunctionName: 'getAllBooks'
      CodeUri: ./build/libs/mybooks-microservice-service-0.0.1-SNAPSHOT-aws.jar
      Runtime: java8
      Timeout: 60
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /getAllBooks
            Method: get
      Environment:
        Variables:
          FUNCTION_NAME: 'getAllBooksResource'

  AddBookEventHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: mybooks.Handler
      FunctionName: 'addBook'
      CodeUri: ./build/libs/mybooks-microservice-service-0.0.1-SNAPSHOT-aws.jar
      Runtime: java8
      Timeout: 60
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /addBook
            Method: post
      Environment:
        Variables:
          FUNCTION_NAME: 'addBookResource'

  LoadBookEventHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: mybooks.Handler
      FunctionName: 'loadBook'
      CodeUri: ./build/libs/mybooks-microservice-service-0.0.1-SNAPSHOT-aws.jar
      Runtime: java8
      Timeout: 60
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /loadBook
            Method: post
      Environment:
        Variables:
          FUNCTION_NAME: 'loadBookResource'
